language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-scalejs-extension' ]; then cd .. && eval "mv $currentfolder generator-scalejs-extension" && cd generator-scalejs-extension; fi

